language: java
deploy:
  provider: codedeploy
  revision_type: github
  access_key_id:
    secure: "i2qmEzbDtZnq+1mqHpRvg8IJP0uMDNSefgwRHbRCZ51PM7M9JfPryT12xRbVNy98EYD6dIwQuwv+jlI4hDpZ22xSxz2gauYB32cuaR+7XbJKIDf4eZYkCPPEtv2dTbOs0zo10jAz5kvHeoROazVb7TlD0BvZvUixpqlnkUFQMIE="
  secret_access_key:
    secure: "TBk5J6v8+jna+bzhSMc1GJAwtTTlDIOLuPYSvFMumT3IV2u+e/OUdgcWc7FSJFUhEY638llajKpQWKdUUkQhGQKpL6gc3TGiQsB/EDH9FJopTbXqYm89rgr25DuUI1s2x6b1fTAgmvsSbfc6oPJkRJESF6HyU/YjlUsnfvAXSx8="
  application: "geoscience-portal-codedeploy"
  deployment_group: "geoscience-portal-group"
  region: "ap-southeast-2"
cache:
  directories:
    - $HOME/.m2
branches:
  only:
    - develop-ga
jdk:
  - oraclejdk8
notifications:
        slack:
                rooms:
                        secure: "Wp5f5vfCj3s/A1hbffVNi3KRurF1EKSi3epI1VcIJTmVSS/SLMAAsiOGCOKFlrFIdd9HB24qNlv56hX15q/CH8libcqwLCoDEuO54O6rusSz/y2PtCIfJnfM1NEk3Nvq7ZdeBiWmsaLBMm1nMRB/3IqQEwvACRLlZJJI5DIl3qo="

